/**
 * What Bolek says on each slide. `{{cue-id}}` marks the moment the orb should
 * fly to the element with that cue id; `[pause]` is a Grok speech tag.
 * Numbers are spelled out so the voice does not guess the Polish declension.
 */
export const NARRATION: Record<string, string> = {
  title: `Cześć! Jestem Bolek, głos tej prezentacji. [pause] Przez najbliższe kilka minut opowiem, jak {{brand}} Droker pomaga zarządowi przewidzieć skutki decyzji, zanim zostaną podjęte. {{tagline}} I jak pamięta, co z tych decyzji wyszło. Zaczynajmy.`,

  problem: `Każda firma codziennie decyduje: o cenie, o zatrudnieniu, o budżecie, o produkcie. [pause] {{scattered}} Wiedza potrzebna do decyzji jest rozproszona: w Slacku, w mailach, w notatkach ze spotkań i w arkuszach z KPI. Nikt nie ma całości. {{claims}} Opinie udają fakty. Sprzedaż mówi, że dwanaście gmin jest zainteresowanych, a pisemne prośby przysłały cztery. {{loop}} A po decyzji nikt nie sprawdza, czy zadziałała. Ta sama pomyłka wraca po roku.`,

  topic: `Wybraliśmy temat pierwszy: Zanim zdecydujesz. Zadanie brzmi: przewidywać skutki decyzji na podstawie wcześniejszych decyzji i ich efektów. [pause] Droker zamyka tę pętlę w całości. {{s1}} Zbiera dane o wcześniejszych decyzjach i KPI. {{s2}} Porównuje scenariusze i pokazuje ich skutki, ryzyka i zależności. {{s3}} Zapisuje decyzję razem z uzasadnieniem i oczekiwanym wynikiem. {{s4}} Monitoruje rzeczywisty efekt. {{s5}} I wykorzystuje tę wiedzę przy kolejnej decyzji. Im więcej decyzji, tym lepiej zna organizację.`,

  graph: `Sercem Drokera jest graf firmy. {{sources}} Podłączamy źródła, które już macie: Slack, skrzynkę mailową, spotkania z Google Meet i arkusze z KPI. {{nodes}} Z nich powstają węzły: osoby, produkty, decyzje, twierdzenia, metryki i obserwacje, połączone relacjami w czasie. {{provenance}} Każde twierdzenie ma autora, datę i dokładny cytat ze źródła. Nic nie jest zmyślone. {{review}} A to, co proponuje model językowy, trafia do grafu dopiero po przeglądzie przez człowieka.`,

  decision: `Zobaczmy to na przykładzie. Fikcyjna firma Aster Systems pyta: budować konektor e-Doręczeń, wziąć partnera, czy poczekać? {{options}} Droker zestawia trzy opcje: własna budowa w szesnaście tygodni, partner w sześć, albo odłożenie decyzji. Z przejrzystą arytmetyką zamiast czarnej skrzynki. {{evidence}} Obok leżą dowody: cztery pisemne prośby klientów kontra dwanaście „zainteresowanych” ze Slacka. I poprzednia funkcja, która miała mieć dwudziestu pięciu klientów, a miała czternastu. {{assumption}} Zmień jedno założenie: czternastu klientów zamiast dwudziestu dwóch, i wynik partnera spada ze stu dziewięćdziesięciu ośmiu do osiemdziesięciu sześciu tysięcy. Prezes widzi, od czego naprawdę zależy decyzja.`,

  loop: `Na decyzji się nie kończy. {{decide}} Dwunastego maja zarząd wybiera pilotaż z partnerem i zapisuje cel: dziesięć płatnych aktywacji w pół roku. {{measure}} Dziewiętnastego listopada Droker importuje wynik: sześć na dziesięć. {{lesson}} Zapisuje lekcję: deklaracje zainteresowania zawyżają gotowość do zakupu. Wymagaj nazwanych zobowiązań. {{next}} I kiedy pojawia się kolejne pytanie, zostać przy partnerze czy budować samemu, ta lekcja i te liczby są już na stole. Tak Droker uczy się firmy.`,

  bolek: `Ta wiedza musi być pod ręką tam, gdzie zapadają decyzje: w sali spotkań. {{ask}} Wystarczy powiedzieć: Bolek, ile płacimy za Pipedrive? Słucham przez Grok Voice, ten sam silnik, którym teraz mówię. {{card}} W niecałą sekundę na ekranie jest karta: tysiąc dwieście dwadzieścia cztery euro za sześć faktur, kto zatwierdził, kto odpowiada, jaki jest limit. {{deterministic}} Karta powstaje deterministycznie z grafu. Model tylko wskazuje, o kogo i o co pytacie, więc nie ma czego zmyślić. {{agent}} A gdy trzeba coś zrobić: napisać mail, zrobić wykres, przygotować raport, przejmuję to jako agent z narzędziami.`,

  agents: `Droker ma też współpracowników: agentów, którzy pracują na grafie między spotkaniami. {{rule}} Ten pilnuje zgłoszeń supportu: cztery zgłoszenia od trzech klientów w sześćdziesiąt dni to wzorzec. {{fires}} Siedemnastego listopada odpala: dziewięć zgłoszeń z czterech gmin o tym samym błędzie. {{proposal}} Dwa dni przed spotkaniem zarządu dokłada do decyzji nową opcję, z cytatem z każdego zgłoszenia. {{pending}} I czeka na akceptację. Agent nigdy sam nie zapisuje faktów w grafie.`,

  stack: `Wszystko działa, nie jest makietą. {{web}} Interfejs i ta prezentacja stoją na TanStack Start. {{graph}} Graf mieszka w SQLite z pełnotekstowym wyszukiwaniem i jawną ontologią relacji. {{voice}} Głos to xAI Grok Voice: rozpoznawanie mowy strumieniowo i synteza z timestampami, dzięki którym wiem, kiedy na co wskazać. {{routing}} Rozumienie wypowiedzi robi model Jev w około trzysta pięćdziesiąt milisekund. {{agent}} Zadania wykonuje agent na Claude z narzędziami. {{tests}} A scenariusze demo są objęte testami i ewaluacjami: pięćdziesiąt jeden z pięćdziesięciu jeden linii.`,

  value: `{{who}} Budujemy to dla prezesa firmy od trzydziestu do stu pięćdziesięciu osób. Ma dane, ale nie ma czasu ich składać. {{how}} Wdrożenie to podłączenie Slacka, poczty i kalendarza. Graf zostaje w firmie, w jednym pliku bazy. {{roadmap}} Dalej: konektory do ERP i CRM, agent co tydzień porównujący cele z KPI, i pilot z pierwszą firmą, najlepiej stąd, z Bielska. {{moat}} Największa wartość rośnie z czasem: każda zapisana decyzja i jej wynik czynią kolejną lepszą.`,

  criteria: `Sprawdźmy się z waszą kartą oceny. {{c-value}} Wartość biznesowa: odpowiadamy na realny problem prezesa, decyzje bez pełnego kontekstu. {{c-deploy}} Wdrożenie: konektory do narzędzi, których firmy już używają, i dane, które nie opuszczają firmy. {{c-innov}} Innowacyjność: pętla od decyzji przez wynik do lekcji, plus agenci, których propozycje przechodzą przegląd. {{c-code}} Kod: graf, głos, agent i testy. Wszystko działa dziś. {{c-creative}} Kreatywność: asystent, który reaguje na imię i nie potrafi zmyślić liczby. {{c-ux}} Łatwość użycia: jedno pytanie głosem, jedna karta. {{c-pitch}} A prezentację… [pause] prowadzi sam produkt.`,

  end: `To wszystko. Droker: firmowy graf decyzji, asystent, który słucha, i pętla, która uczy się z każdej decyzji. {{cta}} Zanim zdecydujesz, zapytaj Bolka. {{team}} Dziękujemy za uwagę. Chętnie odpowiemy na pytania. [pause] A jeśli chcecie, mogę je też usłyszeć.`,
}
