/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as WorkspaceConnectorsRouteImport } from './routes/_workspace/connectors'
import { Route as WorkspaceContextRouteImport } from './routes/_workspace/context'
import { Route as WorkspaceDecisionsRouteImport } from './routes/_workspace/decisions'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as WorkspaceContextIndexRouteImport } from './routes/_workspace/context.index'
import { Route as WorkspaceContextTopicIdRouteImport } from './routes/_workspace/context.$topicId'
import { Route as WorkspaceDecisionsIndexRouteImport } from './routes/_workspace/decisions.index'
import { Route as WorkspaceDecisionsDecisionIdRouteImport } from './routes/_workspace/decisions.$decisionId'
import { Route as WorkspaceDecisionsNewRouteImport } from './routes/_workspace/decisions.new'
import { Route as AppDecisionsIndexRouteImport } from './routes/app/decisions.index'
import { Route as AppDecisionsDecisionIdRouteImport } from './routes/app/decisions.$decisionId'
import { Route as AppMeetingsMeetingIdRouteImport } from './routes/app/meetings.$meetingId'
import { Route as AppNotesNoteIdRouteImport } from './routes/app/notes.$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceConnectorsRoute = WorkspaceConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceContextRoute = WorkspaceContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDecisionsRoute = WorkspaceDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const WorkspaceContextIndexRoute = WorkspaceContextIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceContextRoute,
} as any)
const WorkspaceContextTopicIdRoute = WorkspaceContextTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => WorkspaceContextRoute,
} as any)
const WorkspaceDecisionsIndexRoute = WorkspaceDecisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceDecisionsRoute,
} as any)
const WorkspaceDecisionsDecisionIdRoute =
  WorkspaceDecisionsDecisionIdRouteImport.update({
    id: '/$decisionId',
    path: '/$decisionId',
    getParentRoute: () => WorkspaceDecisionsRoute,
  } as any)
const WorkspaceDecisionsNewRoute = WorkspaceDecisionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspaceDecisionsRoute,
} as any)
const AppDecisionsIndexRoute = AppDecisionsIndexRouteImport.update({
  id: '/decisions/',
  path: '/decisions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDecisionsDecisionIdRoute = AppDecisionsDecisionIdRouteImport.update({
  id: '/decisions/$decisionId',
  path: '/decisions/$decisionId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsMeetingIdRoute = AppMeetingsMeetingIdRouteImport.update({
  id: '/meetings/$meetingId',
  path: '/meetings/$meetingId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/connectors': typeof WorkspaceConnectorsRoute
  '/context': typeof WorkspaceContextRouteWithChildren
  '/decisions': typeof WorkspaceDecisionsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/context/$topicId': typeof WorkspaceContextTopicIdRoute
  '/decisions/$decisionId': typeof WorkspaceDecisionsDecisionIdRoute
  '/decisions/new': typeof WorkspaceDecisionsNewRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/context/': typeof WorkspaceContextIndexRoute
  '/decisions/': typeof WorkspaceDecisionsIndexRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meeting': typeof MeetingRoute
  '/connectors': typeof WorkspaceConnectorsRoute
  '/app': typeof AppIndexRoute
  '/context/$topicId': typeof WorkspaceContextTopicIdRoute
  '/decisions/$decisionId': typeof WorkspaceDecisionsDecisionIdRoute
  '/decisions/new': typeof WorkspaceDecisionsNewRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/context': typeof WorkspaceContextIndexRoute
  '/decisions': typeof WorkspaceDecisionsIndexRoute
  '/app/decisions': typeof AppDecisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/_workspace/connectors': typeof WorkspaceConnectorsRoute
  '/_workspace/context': typeof WorkspaceContextRouteWithChildren
  '/_workspace/decisions': typeof WorkspaceDecisionsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/_workspace/context/$topicId': typeof WorkspaceContextTopicIdRoute
  '/_workspace/decisions/$decisionId': typeof WorkspaceDecisionsDecisionIdRoute
  '/_workspace/decisions/new': typeof WorkspaceDecisionsNewRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_workspace/context/': typeof WorkspaceContextIndexRoute
  '/_workspace/decisions/': typeof WorkspaceDecisionsIndexRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/meeting'
    | '/connectors'
    | '/context'
    | '/decisions'
    | '/app/'
    | '/context/$topicId'
    | '/decisions/$decisionId'
    | '/decisions/new'
    | '/app/decisions/$decisionId'
    | '/app/meetings/$meetingId'
    | '/app/notes/$noteId'
    | '/context/'
    | '/decisions/'
    | '/app/decisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meeting'
    | '/connectors'
    | '/app'
    | '/context/$topicId'
    | '/decisions/$decisionId'
    | '/decisions/new'
    | '/app/decisions/$decisionId'
    | '/app/meetings/$meetingId'
    | '/app/notes/$noteId'
    | '/context'
    | '/decisions'
    | '/app/decisions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/_workspace'
    | '/meeting'
    | '/_workspace/connectors'
    | '/_workspace/context'
    | '/_workspace/decisions'
    | '/app/'
    | '/_workspace/context/$topicId'
    | '/_workspace/decisions/$decisionId'
    | '/_workspace/decisions/new'
    | '/app/decisions/$decisionId'
    | '/app/meetings/$meetingId'
    | '/app/notes/$noteId'
    | '/_workspace/context/'
    | '/_workspace/decisions/'
    | '/app/decisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  MeetingRoute: typeof MeetingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/connectors': {
      id: '/_workspace/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof WorkspaceConnectorsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/context': {
      id: '/_workspace/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof WorkspaceContextRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/decisions': {
      id: '/_workspace/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof WorkspaceDecisionsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_workspace/context/': {
      id: '/_workspace/context/'
      path: '/'
      fullPath: '/context/'
      preLoaderRoute: typeof WorkspaceContextIndexRouteImport
      parentRoute: typeof WorkspaceContextRoute
    }
    '/_workspace/context/$topicId': {
      id: '/_workspace/context/$topicId'
      path: '/$topicId'
      fullPath: '/context/$topicId'
      preLoaderRoute: typeof WorkspaceContextTopicIdRouteImport
      parentRoute: typeof WorkspaceContextRoute
    }
    '/_workspace/decisions/': {
      id: '/_workspace/decisions/'
      path: '/'
      fullPath: '/decisions/'
      preLoaderRoute: typeof WorkspaceDecisionsIndexRouteImport
      parentRoute: typeof WorkspaceDecisionsRoute
    }
    '/_workspace/decisions/$decisionId': {
      id: '/_workspace/decisions/$decisionId'
      path: '/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof WorkspaceDecisionsDecisionIdRouteImport
      parentRoute: typeof WorkspaceDecisionsRoute
    }
    '/_workspace/decisions/new': {
      id: '/_workspace/decisions/new'
      path: '/new'
      fullPath: '/decisions/new'
      preLoaderRoute: typeof WorkspaceDecisionsNewRouteImport
      parentRoute: typeof WorkspaceDecisionsRoute
    }
    '/app/decisions/': {
      id: '/app/decisions/'
      path: '/decisions'
      fullPath: '/app/decisions/'
      preLoaderRoute: typeof AppDecisionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/decisions/$decisionId': {
      id: '/app/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/app/decisions/$decisionId'
      preLoaderRoute: typeof AppDecisionsDecisionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/meetings/$meetingId': {
      id: '/app/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/app/meetings/$meetingId'
      preLoaderRoute: typeof AppMeetingsMeetingIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notes/$noteId': {
      id: '/app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/app/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDecisionsDecisionIdRoute: typeof AppDecisionsDecisionIdRoute
  AppMeetingsMeetingIdRoute: typeof AppMeetingsMeetingIdRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppDecisionsIndexRoute: typeof AppDecisionsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDecisionsDecisionIdRoute: AppDecisionsDecisionIdRoute,
  AppMeetingsMeetingIdRoute: AppMeetingsMeetingIdRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppDecisionsIndexRoute: AppDecisionsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface WorkspaceContextRouteChildren {
  WorkspaceContextTopicIdRoute: typeof WorkspaceContextTopicIdRoute
  WorkspaceContextIndexRoute: typeof WorkspaceContextIndexRoute
}

const WorkspaceContextRouteChildren: WorkspaceContextRouteChildren = {
  WorkspaceContextTopicIdRoute: WorkspaceContextTopicIdRoute,
  WorkspaceContextIndexRoute: WorkspaceContextIndexRoute,
}

const WorkspaceContextRouteWithChildren =
  WorkspaceContextRoute._addFileChildren(WorkspaceContextRouteChildren)

interface WorkspaceDecisionsRouteChildren {
  WorkspaceDecisionsDecisionIdRoute: typeof WorkspaceDecisionsDecisionIdRoute
  WorkspaceDecisionsNewRoute: typeof WorkspaceDecisionsNewRoute
  WorkspaceDecisionsIndexRoute: typeof WorkspaceDecisionsIndexRoute
}

const WorkspaceDecisionsRouteChildren: WorkspaceDecisionsRouteChildren = {
  WorkspaceDecisionsDecisionIdRoute: WorkspaceDecisionsDecisionIdRoute,
  WorkspaceDecisionsNewRoute: WorkspaceDecisionsNewRoute,
  WorkspaceDecisionsIndexRoute: WorkspaceDecisionsIndexRoute,
}

const WorkspaceDecisionsRouteWithChildren =
  WorkspaceDecisionsRoute._addFileChildren(WorkspaceDecisionsRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceConnectorsRoute: typeof WorkspaceConnectorsRoute
  WorkspaceContextRoute: typeof WorkspaceContextRouteWithChildren
  WorkspaceDecisionsRoute: typeof WorkspaceDecisionsRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceConnectorsRoute: WorkspaceConnectorsRoute,
  WorkspaceContextRoute: WorkspaceContextRouteWithChildren,
  WorkspaceDecisionsRoute: WorkspaceDecisionsRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  MeetingRoute: MeetingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
