/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppSessionRouteImport } from './routes/app/session'
import { Route as AppDecisionsIndexRouteImport } from './routes/app/decisions.index'
import { Route as AppDecisionsDecisionIdRouteImport } from './routes/app/decisions.$decisionId'
import { Route as AppMeetingsMeetingIdRouteImport } from './routes/app/meetings.$meetingId'
import { Route as AppNotesNoteIdRouteImport } from './routes/app/notes.$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDecisionsIndexRoute = AppDecisionsIndexRouteImport.update({
  id: '/decisions/',
  path: '/decisions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDecisionsDecisionIdRoute = AppDecisionsDecisionIdRouteImport.update({
  id: '/decisions/$decisionId',
  path: '/decisions/$decisionId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeetingsMeetingIdRoute = AppMeetingsMeetingIdRouteImport.update({
  id: '/meetings/$meetingId',
  path: '/meetings/$meetingId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/session': typeof AppSessionRoute
  '/app/': typeof AppIndexRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/home': typeof AppHomeRoute
  '/app/session': typeof AppSessionRoute
  '/app': typeof AppIndexRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/app/decisions': typeof AppDecisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/session': typeof AppSessionRoute
  '/app/': typeof AppIndexRoute
  '/app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/home'
    | '/app/session'
    | '/app/'
    | '/app/decisions/$decisionId'
    | '/app/meetings/$meetingId'
    | '/app/notes/$noteId'
    | '/app/decisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/home'
    | '/app/session'
    | '/app'
    | '/app/decisions/$decisionId'
    | '/app/meetings/$meetingId'
    | '/app/notes/$noteId'
    | '/app/decisions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/home'
    | '/app/session'
    | '/app/'
    | '/app/decisions/$decisionId'
    | '/app/meetings/$meetingId'
    | '/app/notes/$noteId'
    | '/app/decisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/session': {
      id: '/app/session'
      path: '/session'
      fullPath: '/app/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/decisions/': {
      id: '/app/decisions/'
      path: '/decisions'
      fullPath: '/app/decisions/'
      preLoaderRoute: typeof AppDecisionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/decisions/$decisionId': {
      id: '/app/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/app/decisions/$decisionId'
      preLoaderRoute: typeof AppDecisionsDecisionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/meetings/$meetingId': {
      id: '/app/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/app/meetings/$meetingId'
      preLoaderRoute: typeof AppMeetingsMeetingIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notes/$noteId': {
      id: '/app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/app/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppSessionRoute: typeof AppSessionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDecisionsDecisionIdRoute: typeof AppDecisionsDecisionIdRoute
  AppMeetingsMeetingIdRoute: typeof AppMeetingsMeetingIdRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppDecisionsIndexRoute: typeof AppDecisionsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppSessionRoute: AppSessionRoute,
  AppIndexRoute: AppIndexRoute,
  AppDecisionsDecisionIdRoute: AppDecisionsDecisionIdRoute,
  AppMeetingsMeetingIdRoute: AppMeetingsMeetingIdRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppDecisionsIndexRoute: AppDecisionsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
